name: Build and Publish to npm

on:
  push:
    branches:
      - main  # Or master, depending on your default branch name
    tags:
      - 'v*'  # Ensures action is only run on tagged commits

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'  # Specify the Node.js version you are using
          registry-url: 'https://registry.npmjs.org/'
      
      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build  # Or any other command that prepares your package for publication
      
      - name: Publish to npm
        run: npm publish --access publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
